#!/usr/bin/env bash
# configure web-02 to be identical to web-01
sudo apt-get install -y nginx
sudo sed -i "23i \\\tadd_header X-Served-By: $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
