#!/bin/bash
touch holberton_man_page
.\" Manpage for holberton_man_page.
.\" Contact
.TH man(2) "0.31" "04 May 2015" "man(2)"
.SH NAME
holberton - become a full-stack software engineer
.SH SYNOPSIS
holberton [STUDENTNAME]
.SH DESCRIPTION
Holberton School is a project-based alternative to college for the next generation of software engineers.
.SH OPTIONS
holberton does not take any options. However, you can supply studentname.
.SH SEE ALSO
.I peerlearning(2), projectbased(2), fullstack(2), Betty(1),
.SH BUGS
No known bugs.
.SH Author
Julien Barbier, Sylvain Kalache, Sophie Barbier, Guillaume Salva, Kris Bredemeier, Julien Cyr, Alex Guatier and all the Holberton mentors

0.31 04 May 2015 man(2)
