#!/usr/bin/env bash
# find out what’s keeping your Ubuntu container’s
# Nginx installation from listening on port 80
# Nginx must be running, and listening on port 80
# of all the server’s active IPv4 IPs

sudo service nginx restart
