#!/usr/bin/env bash
# Nginx must be running, and listening on port 80
rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restart
