#!/usr/bin/env bash
# Displays "Holberton School" 10 times but displays "Hi" after the 9th iteration
i="0"
while ((i < 10))
do
    if ((i == 9))
    then echo "Hi"
    fi
       echo "Holberton School"
       i=$((i+1))
done
