#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display hours from 0 to 12
hour="0"
minute="1"
while ((hour < 13))
do
	echo "Hour: $hour"
	while (($minute < 60))
	do
		echo $minute
		minute=$((minute+1))
	done
	hour=$((hour+1))
	minute="1"
done
