#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me redirects to another page
sudo apt-get -y install nginx
sudo echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
