#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me redirects to another page
sudo apt-get -y install nginx
echo "Holberton School" | tee /usr/share/nginx/html/index.html > /dev/null
sudo service nginx restart

sudo sed -i "s|location / {|location /redirect_me {|g"  /etc/nginx/sites-available/default
sudo sed -i "s|try_files \$uri \$uri/ =404;|return 301 https://www.youtube.com/watch?v=5Rswx2Z7SDw" /etc/nginx/sites-available/default
sudo service nginx restart
