#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me redirects to another page
sudo apt-get install -y nginx
fork="/redirect_me"
mew="/etc/nginx/sites-available/default"
ditto="https://www.youtube.com/watch?v=QH2-TGUlwu4"
mewtwo="location $fork $ditto;"
sudo sed -i "$mewtwo" "$mew"
sudo service nginx reload
