#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
sudo pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites_available/default
sudo -u nginx service nginx start